version: '3.8'

services:
  # ??? Motor de Base de Datos Relacional (PostgreSQL)
  postgres_db:
    image: postgres:15-alpine
    container_name: db_proyecto_relacional
    environment:
      POSTGRES_DB: bd_sistema
      POSTGRES_USER: usuario_devops
      POSTGRES_PASSWORD: password_seguro
    ports:
      - "5432:5432"
    networks:
      - red-local-devops
    volumes:
      - datos_postgres_persistentes:/var/lib/postgresql/data

  # ? Microservicio: Backend de Ventas (Spring Boot)
  back-ventas:
    build: ./back-Ventas_SpringBoot/Springboot-API-REST
    container_name: back_ventas_container
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/bd_sistema
      - SPRING_DATASOURCE_USERNAME=usuario_devops
      - SPRING_DATASOURCE_PASSWORD=password_seguro
    depends_on:
      - postgres_db
    networks:
      - red-local-devops

  # ? Microservicio: Backend de Despachos (Spring Boot)
  back-despachos:
    build: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
    container_name: back_despachos_container
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/bd_sistema
      - SPRING_DATASOURCE_USERNAME=usuario_devops
      - SPRING_DATASOURCE_PASSWORD=password_seguro
    depends_on:
      - postgres_db
    networks:
      - red-local-devops

  # ?? Componente de Presentación: Frontend Web
  frontend-app:
    build: ./front_despacho
    container_name: front_despacho_container
    ports:
      - "80:80"
    depends_on:
      - back-ventas
      - back-despachos
    networks:
      - red-local-devops

networks:
  red-local-devops:
    driver: bridge

volumes:
  datos_postgres_persistentes:
