version: '3.8'

services:
  # Base de Datos Relacional (Requisito Obligatorio de la Pauta)
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: user_devops
      POSTGRES_PASSWORD: password_seguro_123
      POSTGRES_DB: bd_proyectos
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - red-interna-devops

  # Backend 1: Ventas
  back-ventas:
    build:
      context: ./back-Ventas_SpringBoot
      dockerfile: Dockerfile
    container_name: back-ventas
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/bd_proyectos
      - SPRING_DATASOURCE_USERNAME=user_devops
      - SPRING_DATASOURCE_PASSWORD=password_seguro_123
    depends_on:
      - postgres-db
    networks:
      - red-interna-devops

  # Backend 2: Despachos
  back-despachos:
    build:
      context: ./back-Despachos_SpringBoot
      dockerfile: Dockerfile
    container_name: back-despachos
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/bd_proyectos
      - SPRING_DATASOURCE_USERNAME=user_devops
      - SPRING_DATASOURCE_PASSWORD=password_seguro_123
    depends_on:
      - postgres-db
    networks:
      - red-interna-devops

  # Frontend: Interfaz Web
  front-despacho:
    build:
      context: ./front_despacho
      dockerfile: Dockerfile
    container_name: front-despacho
    ports:
      - "80:80"
    depends_on:
      - back-ventas
      - back-despachos
    networks:
      - red-interna-devops

volumes:
  db_data:

networks:
  red-interna-devops:
    driver: bridge
