name: Pipeline DevOps - Ciclo Automatico e Infraestructura AWS (IE3)

on:
  push:
    branches: [ "main" ]

jobs:
  devops-core-engine:
    runs-on: ubuntu-latest
    steps:
    # --- FASE 1: CONTROL DE FUENTES Y CONFIGURACIÓN ---
    - name: Descargar Codigo Fuente desde GitHub
      uses: actions/checkout@v4

    - name: Configurar Entorno Java JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # --- FASE 2: COMPILACIÓN NATIVA DE MICROSERVICIOS (BUILD) ---
    - name: Compilar Componente Backend Ventas
      working-directory: ./back-Ventas_SpringBoot/Springboot-API-REST
      run: mvn clean package -DskipTests

    - name: Compilar Componente Backend Despachos
      working-directory: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
      run: mvn clean package -DskipTests

    # --- FASE 3: CONEXIÓN SEGURA Y PASARELA DE ACCESO AWS (SECRETS) ---
    - name: Autenticacion Cifrada en AWS Academy (Minimo Privilegio)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Login de Seguridad en Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # --- FASE 4: REGISTRO INMUTABLE Y TRAZABILIDAD (AMAZON ECR) ---
    - name: Fabricar Repositorios y Publicar Imagenes con Git Tags
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        # Crear los repositorios en la nube si no existen en el registro
        aws ecr create-repository --repository-name back-ventas --region us-east-1 || true
        aws ecr create-repository --repository-name back-despachos --region us-east-1 || true
        aws ecr create-repository --repository-name front-despacho --region us-east-1 || true

        # Compilar y subir Backend Ventas (Con Tag Latest y el SHA inmutable de Git)
        docker build -t $ECR_REGISTRY/back-ventas:latest -t $ECR_REGISTRY/back-ventas:${{ github.sha }} ./back-Ventas_SpringBoot/Springboot-API-REST
        docker push $ECR_REGISTRY/back-ventas --all-tags

        # Compilar y subir Backend Despachos
        docker build -t $ECR_REGISTRY/back-despachos:latest -t $ECR_REGISTRY/back-despachos:${{ github.sha }} ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
        docker push $ECR_REGISTRY/back-despachos --all-tags

        # Compilar y subir Frontend Web
        docker build -t $ECR_REGISTRY/front-despacho:latest -t $ECR_REGISTRY/front-despacho:${{ github.sha }} ./front_despacho
        docker push $ECR_REGISTRY/front-despacho --all-tags

    # --- FASE 5: IMPLEMENTACIÓN DE INFRAESTRUCTURA (TERRAFORM) ---
    - name: Configurar Binarios de Terraform en el Agente CI/CD
      uses: hashicorp/setup-terraform@v3

    - name: Orquestar Infraestructura Real en AWS Cloud
      working-directory: ./terraform
      run: |
        terraform init
        terraform apply -auto-approve
