name: Pipeline DevOps - Ciclo Automatico e Infraestructura AWS (IE3)

on:
  push:
    branches: [ "main" ]

jobs:
  devops-core-engine:
    runs-on: ubuntu-latest
    
    steps:
    - name: Descargar Codigo Fuente desde GitHub
      uses: actions/checkout@v4

    - name: Configurar Entorno Java JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Compilar Componente Backend Ventas
      run: |
        if [ -d "back-Ventas_SpringBoot" ]; then
          cd back-Ventas_SpringBoot && mvn clean package -DskipTests
        else
          echo "Saltando compilacion local"
        fi

    - name: Compilar Componente Backend Despachos
      run: |
        if [ -d "back-Despachos_SpringBoot" ]; then
          cd back-Despachos_SpringBoot && mvn clean package -DskipTests
        else
          echo "Saltando compilacion local"
        fi

    - name: Autenticacion Cifrada en AWS Academy (Minimo Privilegio)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Login de Seguridad en Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Fabricar Repositorios y Publicar Imagenes con Git Tags
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Intentar crear repositorios solo si no existen
        aws ecr describe-repositories --repository-names back-ventas || aws ecr create-repository --repository-name back-ventas
        aws ecr describe-repositories --repository-names back-despachos || aws ecr create-repository --repository-name back-despachos
        aws ecr describe-repositories --repository-names front-despacho || aws ecr create-repository --repository-name front-despacho
        
        # Compilar usando las carpetas como contextos reales
        docker build -t $ECR_REGISTRY/back-ventas:latest -t $ECR_REGISTRY/back-ventas:$IMAGE_TAG ./back-Ventas_SpringBoot
        docker push $ECR_REGISTRY/back-ventas --all-tags
        
        docker build -t $ECR_REGISTRY/back-despachos:latest -t $ECR_REGISTRY/back-despachos:$IMAGE_TAG ./back-Despachos_SpringBoot
        docker push $ECR_REGISTRY/back-despachos --all-tags
        
        docker build -t $ECR_REGISTRY/front-despacho:latest -t $ECR_REGISTRY/front-despacho:$IMAGE_TAG ./front_despacho
        docker push $ECR_REGISTRY/front-despacho --all-tags

    - name: Configurar Binarios de Terraform en el Agente CI/CD
      uses: hashicorp/setup-terraform@v3

    - name: Orquestar Infraestructura Real en AWS Cloud
      run: |
        cd terraform
        terraform init
        terraform apply -auto-approve
